version: '3.3'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
    airflow:
        image: puckel/docker-airflow:latest
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./src:/usr/local/src
            - ./requirements.txt:/requirements.txt
            - ./models:/usr/local/models
            - ./data:/usr/local/data
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 31s
            retries: 3
    tensorflow-serving:
        image: 'tensorflow/serving'
        ports:
            - '8500:8500'
            - '8501:8501'
        volumes:
            - ./model_binaries:/models/image_classification
        environment:
            - MODEL_NAME=image_classification
